# Generated by Django 5.0.6 on 2024-07-12 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parishs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la parroquia.', max_length=20, null=None, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Bautismos', 'Bautismos'), ('Comuniones', 'Comuniones'), ('Confirmaciones', 'Confirmaciones'), ('Matrimonios', 'Matrimonios')], default='Bautismos', max_length=14, null=None)),
                ('identifier', models.CharField(help_text='Identificador único del acta generado automaticamente.', max_length=50, null=None, unique=True)),
                ('description', models.CharField(help_text='Descripción corta del libro, longitud max. 50 caracteres', max_length=50, null=None)),
                ('n_pages', models.IntegerField(choices=[(3, '3'), (100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100, help_text='Número de páginas o folios.')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
                ('modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.parishs')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identificador único de la persona generado automaticamente.', max_length=15, null=None, unique=True)),
                ('firstname', models.CharField(help_text='Nombre completo de la persona.', max_length=50, null=None)),
                ('lastname', models.CharField(help_text='Apellido completo de la persona.', max_length=50, null=None)),
                ('birthplace', models.CharField(help_text='Lugar de nacimiento de la persona', max_length=50, null=None)),
                ('birthday', models.DateField(help_text='Fecha de nacimiento de la persona.', null=None)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', help_text='Genero de la persona.', max_length=9, null=None)),
                ('father_info', models.CharField(help_text='Nombre completo del padre de la persona.', max_length=80, null=None)),
                ('mother_info', models.CharField(help_text='Nombre completo de la madre de la persona.', max_length=80, null=None)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
                ('modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Baptisms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baptism_date', models.DateField(help_text='Fecha en la que se realizo la celebración.', null=None)),
                ('priest', models.CharField(help_text='Sacerdote que realizo la celebración.', max_length=50, null=None)),
                ('parish_priest', models.CharField(help_text='Sacerdote encargado de la parroquia.', max_length=50, null=None)),
                ('godfather1_fullname', models.CharField(help_text='Nombre completo del padrino o madrina del bautisado.', max_length=50, null=None)),
                ('godfather2_fullname', models.CharField(blank=True, help_text='Nombre completo del segundo padrino o madrina del bautisado.', max_length=50, null=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
                ('modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.books')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.persons')),
            ],
        ),
    ]
