# Generated by Django 5.0.6 on 2024-06-13 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Bautismos', 'Bautismos'), ('Comuniones', 'Comuniones'), ('Confirmaciones', 'Confirmaciones'), ('Matrimonios', 'Matrimonios')], default='Bautismos', max_length=14, null=None)),
                ('description', models.CharField(blank=True, help_text='El número de carácteres máximo es de 50', max_length=50, null=True)),
                ('n_pages', models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
                ('modified', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
