# Generated by Django 5.0.6 on 2024-06-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptisms',
            name='identifier',
            field=models.CharField(default='2ZpFHMVwDe3mm4q', max_length=15, null=None),
        ),
        migrations.AlterField(
            model_name='communions',
            name='baptism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.baptisms'),
        ),
        migrations.AlterField(
            model_name='communions',
            name='identifier',
            field=models.CharField(default='tYmiBgrMHa85s9z', max_length=15, null=None),
        ),
    ]
