# Generated by Django 5.0.6 on 2024-07-09 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parishs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=None, unique=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, null=None)),
            ],
        ),
    ]
