# Generated by Django 5.0.6 on 2024-06-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_baptisms_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptisms',
            name='godfather2_fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
