# Generated by Django 5.0.6 on 2024-07-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptisms',
            name='book',
            field=models.ForeignKey(help_text='Seleccionar el Acta dónde se guardar al bautismo.', on_delete=django.db.models.deletion.CASCADE, to='core.books'),
        ),
    ]
