# Generated by Django 5.0.6 on 2024-07-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_baptisms_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptisms',
            name='baptism_date',
            field=models.DateField(help_text='Fecha en la que se celebro la celebración.', null=None),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='baptism_parish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.parishs'),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.books'),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='godfather1_fullname',
            field=models.CharField(help_text='Nombre completo del padrino o madrina del bautisado.', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='godfather2_fullname',
            field=models.CharField(blank=True, help_text='Nombre completo del segundo padrino o madrina del bautisado.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='parish_priest',
            field=models.CharField(help_text='Sacerdote encargado de la parroquia.', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='priest',
            field=models.CharField(help_text='Sacerdote que realizo la celebración.', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='books',
            name='identifier',
            field=models.CharField(help_text='Identificador único del acta generado automaticamente.', max_length=50, null=None, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='n_pages',
            field=models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')], default=100, help_text='Número de páginas o folios.'),
        ),
        migrations.AlterField(
            model_name='parishs',
            name='name',
            field=models.CharField(help_text='Nombre de la parroquia.', max_length=20, null=None, unique=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birthday',
            field=models.DateField(help_text='Fecha de nacimiento de la persona.', null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='birthplace',
            field=models.CharField(help_text='Lugar de nacimiento de la persona', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='father_info',
            field=models.CharField(help_text='Nombre completo del padre de la persona.', max_length=80, null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='firstname',
            field=models.CharField(help_text='Nombre completo de la persona.', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', help_text='Genero de la persona.', max_length=9, null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='identifier',
            field=models.CharField(help_text='Identificador único de la persona generado automaticamente.', max_length=15, null=None, unique=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='lastname',
            field=models.CharField(help_text='Apellido completo de la persona.', max_length=50, null=None),
        ),
        migrations.AlterField(
            model_name='persons',
            name='mother_info',
            field=models.CharField(help_text='Nombre completo de la madre de la persona.', max_length=80, null=None),
        ),
    ]
