# Generated by Django 5.0.6 on 2024-07-09 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_baptisms_baptism_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baptisms',
            name='baptism_date',
            field=models.DateField(help_text='Fecha en la que se realizo la celebración.', null=None),
        ),
        migrations.AlterField(
            model_name='baptisms',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persons', unique=True),
        ),
    ]
